In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import torch as t
print(t.__version__)

2.9.1+cu128


### creating tensor

In [3]:
## scalar
scaler = t.tensor(7)
scaler

tensor(7)

In [4]:
scaler.item() ## tensor back as python int

7

In [5]:
## vector
vector = t.tensor([7,7]) 
vector

tensor([7, 7])

In [6]:
vector.ndim 

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
## matrix 
matrix = t.tensor([[3,1,2],
                  [3,4,7],
                  [8,9,19]])
matrix

tensor([[ 3,  1,  2],
        [ 3,  4,  7],
        [ 8,  9, 19]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([3, 3])

In [11]:
## tensor 
TENSOR = t.tensor([[[1,2,3],
                    [4,5,6],
                    [6,7,8]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [15]:
TENSOR[1:1]

tensor([], size=(0, 3, 3), dtype=torch.int64)

## Random tensor


In [16]:
##  creating with pytorch of size(3,4)
random_tensor = t.rand((3,4))
random_tensor 

tensor([[0.3600, 0.2150, 0.5678, 0.8435],
        [0.9623, 0.6240, 0.1074, 0.9876],
        [0.3401, 0.3428, 0.4289, 0.4030]])

In [17]:
random_tensor.ndim

2

In [18]:
##   create random tensor with simllar shape to an image

random_image_size_tensor = t.rand(size=(244,244,3))
 

In [19]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [20]:
## zeros and ones
zeros = t.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
## let's try multiplying 
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = t.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
## creating range of tensors
one_to_ten = t.arange(1,11,1)

In [25]:
## tensors like
ten_zeros = t.zeros_like(input=one_to_ten) ## same shape as one_to_10
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
## Tensor datatype
#float32 tensor
float_32_tensor = t.tensor([3.0,6.0,9.0],
                           dtype=t.float32,
                           device=None,  # cuda or cpu or what device is your tensor on
                            requires_grad=False)  # Whether or not to track gradient with these tensor operation
float_32_tensor                           

tensor([3., 6., 9.])

* If dtype= written None it will still gives float32 as it's default

* Float32 means a number will take 32 bits of storage in memory of computer float16 will take 16 bit of memory in computer

* ' Tensor datatype is one of the three big issues in Python And deep learning basically you will tackle as an error while writing the code Remember this'
1. tensor not right dtatype
2. tensor not right shape
3. tensors not on the right device (cpu or gpu)



In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(t.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor.dtype

torch.float16

In [30]:
float_16_tensor * float_32_tensor                 

tensor([ 9., 36., 81.])